---
# roles/base/defaults/main.yml

# Pacotes essenciais a instalar no setup base
base_packages:
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - unzip
  - git
  - jq
  - locales
  - systemd-timesyncd

# Swap configuration
swap_enabled: true
swap_size: "1G"
swap_swappiness: 10
swap_file: /swapfile

# NTP servers
ntp_servers:
  - "0.debian.pool.ntp.org"
  - "1.debian.pool.ntp.org"
ntp_fallback_servers:
  - "2.debian.pool.ntp.org"
  - "3.debian.pool.ntp.org"

# Locale padr√£o do sistema
base_locale: en_US.UTF-8
